export const NON_INTERSECTION_QUESTIONS_PER_EXAM = 34;
export const INTERSECTION_QUESTIONS_PER_EXAM = 4;
export const QUESTIONS_PER_EXAM = NON_INTERSECTION_QUESTIONS_PER_EXAM + INTERSECTION_QUESTIONS_PER_EXAM;
export const MIN_CORRECT_NON_INTERSECTION_ANSWERS_FOR_PASS = NON_INTERSECTION_QUESTIONS_PER_EXAM - 4 ;